use axum::{
    routing::{get, post},
    Json, Router,
};
use base64::Engine;
use chrono::Utc;
use jsonwebtoken::{Algorithm, EncodingKey, Header};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::net::SocketAddr;
use tracing::{info, warn, Level};
use uuid::Uuid;

const PRIVATE_KEY_PEM: &str = include_str!("../keys/private.pem");
const _PUBLIC_KEY_PEM: &str = include_str!("../keys/public.pem");

// Static modulus hex extracted from the public key generated by openssl
const MODULUS_HEX: &str = "DF5F5367D3AC2D124CB28DDDA9EC7C9578816DDF823885AA9258766ED663022A667B94C048A92D586FA95903BE9A762ECA6DD4E7DC8640B8AAE192521163C090DCE5FDCA18DAADFE4AE34D8B505182D40712C70A6CD08A0F2D4350700CC23D962977C998DAE25B5012B93C57B17D6F10543D0DCAE3E22416E92818DAD345B6B4E7F2DAAB43CD2C931896BCCC8D2DBE17A96651E41BE1CBA98FC701EAC54222AA8E0592A850C5F06CDB0C42323015FD7BD0EB4DF2A676BBA8749F5EB31604C9D88428B25A48ECE560DA90ABB5E8E581DB161084D2D89114246FE34D244A1B81737EC39311FAB780EE1D4B87DD2BDE0F8004DC7FF7C1F66595094FA23E27CE6F69";

#[derive(Debug, Serialize, Deserialize)]
struct McpClaims {
    sub: String,
    aud: String,
    tenant_id: String,
    workspace_id: String,
    agent_id: String,
    run_id: String,
    task_id: String,
    scopes: Vec<String>,
    max_risk: String,
    delegated_by: String,
    jti: String,
    exp: usize,
}

#[derive(Debug, Deserialize)]
struct BootstrapRequest {
    workload_token: String,
    run_id: String,
    task_id: String,
    agent_id: String,
}

#[derive(Debug, Serialize)]
struct BootstrapResponse {
    access_token: String,
    expires_in: u64,
}

#[tokio::main]
async fn main() -> std::result::Result<(), anyhow::Error> {
    aivcs_core::init_tracing(false, Level::INFO);
    info!("🚀 aivcs-auth starting");

    let app = Router::new()
        .route("/health", get(health_check))
        .route("/.well-known/jwks.json", get(jwks))
        .route("/v1/auth/bootstrap", post(bootstrap));

    let addr = SocketAddr::from(([0, 0, 0, 0], 8081));
    let listener = tokio::net::TcpListener::bind(addr).await?;
    info!("📡 listening on {}", addr);

    axum::serve(listener, app).await?;
    Ok(())
}

async fn health_check() -> Json<Value> {
    Json(json!({
        "status": "healthy",
        "service": "aivcs-auth",
        "timestamp": Utc::now()
    }))
}

async fn jwks() -> Json<Value> {
    // Dynamically base64url encode the modulus at request-time or load.
    let modulus_bytes = hex::decode(MODULUS_HEX).unwrap_or_default();
    let n_b64 = base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(modulus_bytes);

    Json(json!({
        "keys": [
            {
                "kty": "RSA",
                "use": "sig",
                "alg": "RS256",
                "kid": "key-id-aivcs",
                "n": n_b64,
                "e": "AQAB"
            }
        ]
    }))
}

async fn bootstrap(
    Json(req): Json<BootstrapRequest>,
) -> std::result::Result<Json<BootstrapResponse>, axum::http::StatusCode> {
    info!(
        "Exchange workload identity for run={} task={} agent={}",
        req.run_id, req.task_id, req.agent_id
    );

    // Validate workload token (mock validation in dev mode)
    if req.workload_token.is_empty() {
        warn!("Bootstrap failed: empty workload token");
        return Err(axum::http::StatusCode::BAD_REQUEST);
    }

    // Load signing key
    let encoding_key = match EncodingKey::from_rsa_pem(PRIVATE_KEY_PEM.as_bytes()) {
        Ok(key) => key,
        Err(err) => {
            warn!("Failed to load RSA private key: {}", err);
            return Err(axum::http::StatusCode::INTERNAL_SERVER_ERROR);
        }
    };

    // Calculate expiry (10 minutes from now)
    let exp = (Utc::now() + chrono::Duration::minutes(10)).timestamp() as usize;
    let jti = Uuid::new_v4().to_string();

    let claims = McpClaims {
        sub: format!("agent_instance:{}", Uuid::new_v4()),
        aud: "https://mcp.aivcs.lornu.ai".to_string(),
        tenant_id: "tenant-default".to_string(),
        workspace_id: "ws-default".to_string(),
        agent_id: req.agent_id,
        run_id: req.run_id,
        task_id: req.task_id,
        scopes: vec![
            "repo.diff.read".to_string(),
            "repo.diff.write".to_string(),
            "repo.merge.execute".to_string(),
        ],
        max_risk: "write".to_string(),
        delegated_by: "policy:builder-feature-branch-write".to_string(),
        jti,
        exp,
    };

    let mut header = Header::new(Algorithm::RS256);
    header.kid = Some("key-id-aivcs".to_string());

    match jsonwebtoken::encode(&header, &claims, &encoding_key) {
        Ok(token) => Ok(Json(BootstrapResponse {
            access_token: token,
            expires_in: 600,
        })),
        Err(err) => {
            warn!("JWT encoding failed: {}", err);
            Err(axum::http::StatusCode::INTERNAL_SERVER_ERROR)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::http::StatusCode;
    use tower::ServiceExt;

    async fn setup_router() -> Router {
        Router::new()
            .route("/health", get(health_check))
            .route("/.well-known/jwks.json", get(jwks))
            .route("/v1/auth/bootstrap", post(bootstrap))
    }

    #[tokio::test]
    async fn test_jwks_endpoint() {
        let app = setup_router().await;
        let req = axum::http::Request::builder()
            .uri("/.well-known/jwks.json")
            .body(axum::body::Body::empty())
            .unwrap();

        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::OK);

        let body_bytes = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        let json: Value = serde_json::from_slice(&body_bytes).unwrap();

        let keys = json["keys"].as_array().unwrap();
        assert_eq!(keys.len(), 1);
        assert_eq!(keys[0]["kty"], "RSA");
        assert_eq!(keys[0]["kid"], "key-id-aivcs");
        assert!(keys[0]["n"].as_str().is_some());
        assert_eq!(keys[0]["e"], "AQAB");
    }

    #[tokio::test]
    async fn test_bootstrap_endpoint() {
        let app = setup_router().await;
        let req_body = json!({
            "workload_token": "mock-workload-token-xyz",
            "run_id": "run-123",
            "task_id": "task-456",
            "agent_id": "agent-789"
        });

        let req = axum::http::Request::builder()
            .method("POST")
            .uri("/v1/auth/bootstrap")
            .header("content-type", "application/json")
            .body(axum::body::Body::from(
                serde_json::to_vec(&req_body).unwrap(),
            ))
            .unwrap();

        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::OK);

        let body_bytes = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        let json: Value = serde_json::from_slice(&body_bytes).unwrap();

        let token = json["access_token"].as_str().unwrap();
        assert!(!token.is_empty());
        assert_eq!(json["expires_in"], 600);

        // Decode and verify token using the public key
        let public_key = include_str!("../keys/public.pem");
        let dec_key = jsonwebtoken::DecodingKey::from_rsa_pem(public_key.as_bytes()).unwrap();
        let mut validation = jsonwebtoken::Validation::new(jsonwebtoken::Algorithm::RS256);
        validation.set_audience(&["https://mcp.aivcs.lornu.ai"]);

        let token_data = jsonwebtoken::decode::<McpClaims>(token, &dec_key, &validation).unwrap();
        let claims = token_data.claims;
        assert!(claims.sub.starts_with("agent_instance:"));
        assert_eq!(claims.agent_id, "agent-789");
        assert_eq!(claims.run_id, "run-123");
        assert_eq!(claims.task_id, "task-456");
        assert_eq!(claims.max_risk, "write");
        assert!(claims.scopes.contains(&"repo.diff.read".to_string()));
    }

    #[tokio::test]
    async fn test_bootstrap_empty_token() {
        let app = setup_router().await;
        let req_body = json!({
            "workload_token": "",
            "run_id": "run-123",
            "task_id": "task-456",
            "agent_id": "agent-789"
        });

        let req = axum::http::Request::builder()
            .method("POST")
            .uri("/v1/auth/bootstrap")
            .header("content-type", "application/json")
            .body(axum::body::Body::from(
                serde_json::to_vec(&req_body).unwrap(),
            ))
            .unwrap();

        let response = app.oneshot(req).await.unwrap();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
    }
}
