[profile.default]
retries = 1
test-threads = "num-cpus"
fail-fast = false
status-level = "pass"

[profile.ci]
retries = 2
test-threads = "num-cpus"
fail-fast = false
status-level = "fail"
final-status-level = "flaky"
